server:
  port: 3010
  origin: '*'

db:
  type: 'postgres'
  host: 'localhost'
  port: '5442'
  database: 'companyprofiletest'
  username: 'companyprofiletest'
  password: 'companyprofiletest'
  synchronize: false

jwt:
  REDIS_TEST_HOST: 'localhost'
  REDIS_TEST_PORT: '6392'
  TOKEN_TEST_DATABASE: '0'
  JWT_SECRET: 'globalfy_accesstoken'
  CACHE_TOKEN_SECRET: 'abcdefg'
  JWT_SECRET_EXPIRES_IN: '30m'
