server:
  port: 3010
  origin: '*'

db:
  type: 'postgres'
  host: 'localhost'
  port: '5441'
  database: 'companyprofile'
  username: 'companyprofile'
  password: 'companyprofile'
  synchronize: false

jwt:
  REDIS_HOST: 'localhost'
  REDIS_PORT: '6391'
  TOKEN_DATABASE: '0'
  REDIS_PASSWORD: '123'
  REDIS_TEST_HOST: 'localhost'
  REDIS_TEST_PORT: '6392'
  TOKEN_TEST_DATABASE: '0'
  JWT_SECRET: 'globalfy_accesstoken'
  CACHE_TOKEN_SECRET: 'abcdefg'
  JWT_SECRET_EXPIRES_IN: '30m'
