server:
  port: 3015
  origin: '*'

db:
  type: 'postgres'
  host: 'localhost'
  port: '5451'
  database: 'bitscraper'
  username: 'bitscraper'
  password: 'bitscraper'
  synchronize: false

jwt:
  REDIS_HOST: 'localhost'
  REDIS_PORT: '6398'
  TOKEN_DATABASE: '0'
  REDIS_PASSWORD: '123'
  REDIS_TEST_HOST: 'localhost'
  REDIS_TEST_PORT: '6398'
  TOKEN_TEST_DATABASE: '0'
  JWT_SECRET: 'bitscraper_accesstoken'
  CACHE_TOKEN_SECRET: 'abcdefg'
  JWT_SECRET_EXPIRES_IN: '30m'
