version: '3'
services:
  bit-scraper-db:
    container_name: bit-scraper-db
    image: postgres
    environment:
      POSTGRES_USER: bitscraper
      POSTGRES_PASSWORD: bitscraper
      POSTGRES_DB: bitscraper
    ports:
      - '5451:5432'
    networks:
      - bit-scraper-net
    volumes:
      - bit-scraper-db-vol:/var/lib/postgresql/data

  bit-scraper-db-test:
    container_name: bit-scraper-db-test
    image: postgres
    environment:
      POSTGRES_USER: bitscrapertest
      POSTGRES_PASSWORD: bitscrapertest
      POSTGRES_DB: bitscrapertest
    ports:
      - '5452:5432'
    networks:
      - bit-scraper-net

  bit-scraper-redis:
    image: 'redis:3.2.6'
    container_name: bit-scraper-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6398:6379'
    volumes:
      - './.redis_data:/data'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - bit-scraper-net

  bit-scraper-redis-test:
    image: 'redis:3.2.6'
    container_name: bit-scraper-redis-test
    ports:
      - '6399:6379'
    volumes:
      - './.redis_data:/data'
    networks:
      - bit-scraper-net

volumes:
  bit-scraper-db-vol: {}

networks:
  bit-scraper-net:
    driver: bridge
